"""Write docs/GAMES.md from the game profiles, so the docs never drift.

Run:  .venv\\Scripts\\python.exe tools\\games_doc.py
A test fails if docs/GAMES.md is out of date with app/core/games.py.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.core import games  # noqa: E402

OUT = ROOT / "docs" / "GAMES.md"


def render() -> str:
    lines = [
        "# Setting up each game",
        "",
        "<!-- Generated by tools/games_doc.py from app/core/games.py. Edit those, not this. -->",
        "",
        "The same guide is in the app: open a game's world menu and choose",
        "*How to set up*, or use the link during setup.",
        "",
        "## Every game",
        "",
    ]
    lines += [f"- {line}" for line in games.COMMON_STEPS]
    lines.append("")
    lines.append("| Game | Status |")
    lines.append("|---|---|")
    for g in games.ALL:
        anchor = g.name.lower().replace(":", "").replace(" ", "-")
        lines.append(f"| [{g.name}](#{anchor}) | {'Tested' if g.verified else 'Beta'} |")
    for g in games.ALL:
        lines += ["", f"## {g.name}", ""]
        if not g.verified:
            lines += ["*Beta: the save layout follows community guides and WorldSync's own "
                      "tests. Every overwrite is backed up first; reports on GitHub move it "
                      "to tested.*", ""]
        for i, step in enumerate(games.setup_steps(g), 1):
            lines.append(f"{i}. {step}")
        lines += ["", "**Where the saves live**", ""]
        for template in g.save_roots:
            lines.append(f"- `{games.human_save_path(template)}`")
        lines += ["", f"WorldSync calls one of these a *{g.world_word}*. {g.world_hint}"]
    lines.append("")
    return "\n".join(lines)


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
